### ISSUE TITLE
Bulk and Single cell tests were failing because of error: java.nio.file.NoSuchFileException: null/gxa/species-properties.json

### ISSUE THREAD

**Issue by upendrakumbham** [ebi-gene-expression-group/atlas-web-single-cell#170]
When I run `gradle build or ./gradlew build` on Bulk and Single Cell project 

Test cases are failing because of the path error of  `species-properties.json`.

In the Single Cell project, 60 tests were failed with the error:` java.nio.file.NoSuchFileException: null/gxa/species-properties.json`

In the bulk project, 45 tests were failed with the error:` java.nio.file.NoSuchFileException: null/gxa/species-properties.json`

**Comment by upendrakumbham** [comment]
This issue is common in both projects in the `develop` branches.

Looks like something got changed from the previous while upgrading to a new workflow.

I and Pablo had a meeting on `16th of June` to debug on the docker-compose side to see whether we have species-properties.json on the right path in the docker volume or not?

is there any issue with the docker volumes?

Then, we came to knew that after debug, there is no issue with the docker-compose setup. Container loading `species-properites.json` file on the right location.

I did debug in the codebase to trace out the exception:` java.nio.file.NoSuchFileException: null/gxa/species-properties.json`

Here is a class where it is throwing an exception:  AtlasResource is an underlying abstract class where we defined the path to load
the `species-properites.json` file. This path returning null, so further process failing... 

![image](https://user-images.githubusercontent.com/15771356/122385681-01932880-cf65-11eb-9771-54ab7c788c4e.png)

**Comment by upendrakumbham** [comment]
Error trace of one test case: 

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'baselineExperimentFactory' defined in URL [jar:file:/Users/ukumbham/atlas/atlas-web-bulk/atlas-web-core/build/libs/atlas-web-core-1.0.0.jar!/uk/ac/ebi/atlas/trader/factory/BaselineExperimentFactory.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'speciesFactory' defined in URL [jar:file:/Users/ukumbham/atlas/atlas-web-bulk/atlas-web-core/build/libs/atlas-web-core-1.0.0.jar!/uk/ac/ebi/atlas/species/SpeciesFactory.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'speciesPropertiesTrader': Invocation of init method failed; nested exception is java.io.UncheckedIOException: java.nio.file.NoSuchFileException: null/gxa/species-properties.json`

```
Caused by: java.nio.file.NoSuchFileException: null/gxa/species-properties.json
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2838)
	at uk.ac.ebi.atlas.model.resource.JsonFile$ReadOnly.get(JsonFile.java:26)
	... 225 more
```

**Comment by upendrakumbham** [comment]
[Error Stack trace:.pdf](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/files/6669766/Error.Stack.trace.pdf)

**Comment by upendrakumbham** [comment]
This issue got resolved by compiling java classes following way:

```
./gradlew \
  -PdataFilesLocation=/Users/ukumbham/ATLAS3.TEST/integration-test-data/gxa/filesystem \
  -PexperimentFilesLocation=/Users/ukumbham/ATLAS3.TEST/integration-test-data/gxa/filesystem/gxa \
  -PzkHost=gxa-zk-1 \
  -PsolrHost=gxa-solrcloud-1 \
  :app:clean :app:testClasse
```
So, closing this issue.
